apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: goapp-deployment
spec:
  selector:
    matchLabels:
      app: goapp
  replicas: 5
  template:
    metadata:
      labels:
        app: goapp
        dev: mcclayac
        devname: Anthony_McClay
        version: v0.0.5
    spec:
      containers:
        - name: goapp
          image: mcclayac/goservice9090:v0.0.5
          ports:
            - containerPort: 9090

