apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pythonapp-deployment
spec:
  selector:
    matchLabels:
      app: pythonapp
  replicas: 1
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
        - name: pythonapp
          image: mcclayac/pythonservice9292:v0.0.4
          ports:
            - containerPort: 9292
